[build]
  command = "corepack enable && pnpm install && pnpm run build"
  publish = "build"
  environment = { NODE_VERSION = "18.17.1", NODE_OPTIONS = "--openssl-legacy-provider", NPM_FLAGS = "--force" }


